version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: dev_db_doj_ocr_webapp
      POSTGRES_USER: usr_headless
      POSTGRES_PASSWORD: pswd_headless
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ocr_network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app/config.env
    container_name: ocr_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - ocr_network

volumes:
  postgres_data:

networks:
  ocr_network:  # Define a custom network
    driver: bridge
